# Gitlab CI Script for astrocyte/rnaseq
# Brandi L. Cantarel - 2017

variables:
  TEST_BRANCH: "master"
  GIT_SUBMODULE_STATEGY: recursive

before_script:
  - module load nextflow/0.27.6
  - ln -s /project/shared/bicf_workflow_ref/workflow_testdata/rnaseq test_data

stages:
  - integration

test_human:
  stage: integration
  script:
    - nextflow run workflow/main.nf --design  /project/shared/bicf_workflow_ref/workflow_testdata/rnaseq/design.rnaseq.txt --input  /project/shared/bicf_workflow_ref/workflow_testdata/rnaseq --output human_output
  artifacts:
    expire_in: 2 days

test_mouse:
  stage: integration
  script:
    - nextflow run workflow/main.nf --input  /project/shared/bicf_workflow_ref/workflow_testdata/rnaseq --design /project/shared/bicf_workflow_ref/workflow_testdata/mouse_se.design.txt --pairs se --fusion skip --genome /project/shared/bicf_workflow_ref/GRCm38 --markdups null --output mouse_output
  artifacts:
    expire_in: 2 days
